/home/a/acer/typelib/repos/DLL-Injection/DllInjection/DllInjection/bin/Release/DllInjection.exe
/home/a/acer/typelib/repos/DLL-Injection/DllInjection/DllInjection/obj/Debug/DllInjection.exe
/home/a/acer/typelib/repos/DLL-Injection/DllInjection/DllInjection/obj/Release/DllInjection.exe
/home/a/acer/typelib/repos/DLL-Injection/DllInjection/DllInjection/obj/x64/Debug/DllInjection.exe
/home/a/acer/typelib/repos/DLL-Injection/DllInjection/DllInjection/obj/x64/Release/DllInjection.exe
/home/a/acer/typelib/repos/k8fly/bin/Debug/K8fly.exe
/home/a/acer/typelib/repos/k8fly/obj/x86/Debug/K8fly.exe
/home/a/acer/typelib/repos/Aggressor/Cscan.exe
/home/a/acer/typelib/repos/RexCrypter/Crypter/Crypter/bin/Debug/REXCRY.exe
/home/a/acer/typelib/repos/RexCrypter/Crypter/Crypter/obj/Debug/REXCRY.exe
/home/a/acer/typelib/repos/gray-keylogger-2/Gray\ Keylogger\ 2/Executer.exe
/home/a/acer/typelib/repos/gray-keylogger-2/Gray\ Keylogger\ 2/Gray\ Keylogger\ 2.exe
/home/a/acer/typelib/repos/gray-keylogger-2/Gray\ Keylogger\ 2\ Source\ code/Form/bin/Debug/Executer.exe
/home/a/acer/typelib/repos/gray-keylogger-2/Gray\ Keylogger\ 2\ Source\ code/Form/bin/Debug/Gray\ Keylogger\ 2.exe
/home/a/acer/typelib/repos/WhiteListEvasion/IEExec/test64/bin/x64/Debug/test64.exe
/home/a/acer/typelib/repos/WhiteListEvasion/IEExec/test64/bin/x64/Release/test64.exe
/home/a/acer/typelib/repos/WhiteListEvasion/IEExec/test64/obj/x64/Debug/test64.exe
/home/a/acer/typelib/repos/WhiteListEvasion/IEExec/test64/obj/x64/Release/test64.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/bin/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/bin/x64/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/obj/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/bin/Debug/NtApiDotNet.dll
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/bin/x64/Debug/NtApiDotNet.dll
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/obj/x64/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Edge/bin/x64/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Edge/obj/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Edge/obj/x64/Debug/AppxExploit.exe
/home/a/acer/typelib/repos/SharpSniper/bin/Release/SharpSniper.exe
/home/a/acer/typelib/repos/SharpSniper/obj/Debug/SharpSniper.exe
/home/a/acer/typelib/repos/CVE-2019-1253/AppxExploit_Cortana/lib/NtApiDotNet.dll
/home/a/acer/typelib/repos/gray-keylogger-2/Gray\ Keylogger\ 2/Executer_hidden.exe
/home/a/acer/typelib/repos/SharpSniper/obj/Release/SharpSniper.exe
/home/a/acer/typelib/repos/DarkEye/BasicCryptorFromDebil/Jopa/bin/Debug/Jopa.exe
/home/a/acer/typelib/repos/DarkEye/BasicCryptorFromDebil/Jopa/bin/Release/Jopa.exe
/home/a/acer/typelib/repos/DarkEye/BasicCryptorFromDebil/Jopa/obj/Debug/Jopa.exe
/home/a/acer/typelib/repos/DarkEye/BasicCryptorFromDebil/Jopa/obj/Release/Jopa.exe
/home/a/acer/typelib/repos/scout/dist/scout_net35.exe
/home/a/acer/typelib/repos/scout/dist/scout_net45.exe
/home/a/acer/typelib/repos/SharpLoginPrompt/SharpLoginPrompt/bin/Debug/SharpLoginPrompt.exe
/home/a/acer/typelib/repos/SharpLoginPrompt/SharpLoginPrompt/obj/Debug/SharpLoginPrompt.exe
/home/a/acer/typelib/repos/SharpLoginPrompt/SharpLoginPrompt/obj/Release/SharpLoginPrompt.exe
/home/a/acer/typelib/repos/SharpLoginPrompt/SharpLoginPrompt/bin/Release/SharpLoginPrompt.exe
/home/a/acer/typelib/repos/PSByPassCLM/PSBypassCLM/PSBypassCLM/bin/Debug/PsBypassCLM.exe
/home/a/acer/typelib/repos/PSByPassCLM/PSBypassCLM/PSBypassCLM/bin/x64/Debug/PsBypassCLM.exe
/home/a/acer/typelib/repos/PSByPassCLM/PSBypassCLM/PSBypassCLM/obj/x64/Debug/PsBypassCLM.exe
/home/a/acer/typelib/repos/PSByPassCLM/PSBypassCLM/PSBypassCLM/obj/Debug/PsBy2.exe
/home/a/acer/typelib/repos/PSByPassCLM/PSBypassCLM/PSBypassCLM/obj/Debug/PsBypassCLM.exe
/home/a/acer/typelib/repos/BlackNET/BlackNET\ Panel/plugins/FileSearcher.dll
/home/a/acer/typelib/repos/BlackNET/BlackNET\ Panel/plugins/PasswordStealer.dll
/home/a/acer/typelib/repos/BlackNET/BlackNET\ -\ Compiled/stub.exe
/home/a/acer/typelib/repos/BlackNET/BlackNET\ -\ Compiled/BlackNET\ Builder.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/x64/Debug/WindowsFormsApp1.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/Debug/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/Release/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/x64/Release/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/x86/Debug/WindowsFormsApp1.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/bin/x86/Release/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/Debug/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/Release/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/x64/Debug/WindowsFormsApp1.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/x86/Debug/WindowsFormsApp1.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/x86/Release/AvIator.exe
/home/a/acer/typelib/repos/AVIator/WindowsFormsApp1/WindowsFormsApp1/obj/x64/Release/AvIator.exe
/home/a/acer/typelib/repos/TeleShadow2/Release/stubx
/home/a/acer/typelib/repos/TeleShadow2/Release/TeleShadow.exe
/home/a/acer/typelib/repos/LethalHTA/CobaltStrike/LethalHTADotNet.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/Obfuscated\ Releases/winPEASany.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/Obfuscated\ Releases/winPEASx64.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/Obfuscated\ Releases/winPEASx86.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/Release/Dotfuscated/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/x64/Release/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/bin/x86/Release/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/obj/Debug/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/obj/Release/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/obj/x64/Release/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/obj/x86/Debug/winPEAS.exe
/home/a/acer/typelib/repos/privilege-escalation-awesome-scripts-suite/winPEAS/winPEASexe/winPEAS/obj/x86/Release/winPEAS.exe
/home/a/acer/typelib/repos/SharpStat/SharpStat.exe
/home/a/acer/typelib/repos/SharpStat/SharpStat/bin/Debug/SharpStat.exe
/home/a/acer/typelib/repos/SharpStat/SharpStat/bin/Release/SharpStat.exe
/home/a/acer/typelib/repos/SharpStat/SharpStat/obj/Debug/SharpStat.exe
/home/a/acer/typelib/repos/SharpStat/SharpStat/obj/Release/SharpStat.exe
/home/a/acer/typelib/repos/SneakyService/SneakyService/bin/Debug/Program.exe
/home/a/acer/typelib/repos/SneakyService/SneakyService/obj/Debug/Program.exe
/home/a/acer/typelib/repos/Lime-RAT/Project/Plugins/ENC/Resources/DECF.exe
/home/a/acer/typelib/repos/Lime-RAT/Project/Plugins/PERS/Resources/DLL.dll
/home/a/acer/typelib/repos/DInvoke_PoC/DInvoke_PoC/obj/Debug/DInvoke_PoC.exe
/home/a/acer/typelib/repos/DInvoke_PoC/DInvoke_PoC/bin/Debug/DInvoke_PoC.exe
/home/a/acer/typelib/repos/ReverseShell/ReverseRat_Server_Console/ReverseRat_Server_Console/bin/Debug/ReverseRat_Server_Console.exe
/home/a/acer/typelib/repos/ReverseShell/ReverseRat_Server_Console/ReverseRat_Server_Console/obj/Debug/ReverseRat_Server_Console.exe
/home/a/acer/typelib/repos/ReverseShell/ReverseRatClient/ReverseRatClient/bin/Debug/ReverseRatClient.exe
/home/a/acer/typelib/repos/ReverseShell/ReverseRatClient/ReverseRatClient/obj/Debug/ReverseRatClient.exe
/home/a/acer/typelib/repos/SneakyExec/SneakyExec/obj/Debug/DownloadAndExec.exe
/home/a/acer/typelib/repos/K8tools/SharpUp.exe
/home/a/acer/typelib/repos/EvilWMIProvider/EvilWMIProvider/bin/Release/EvilWMIProvider.dll
/home/a/acer/typelib/repos/SharpChisel/SharpChisel/obj/Release/SharpChisel.exe
/home/a/acer/typelib/repos/SharpChisel/SharpChisel/obj/Debug/SharpChisel.exe
/home/a/acer/typelib/repos/SharpChisel/SharpChisel/bin/Release/SharpChisel.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/LockLess.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpRoast.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpDPAPI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpRoast.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpUp.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/Seatbelt.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/LockLess.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpDump.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpDPAPI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpRoast.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpUp.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpDump.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/Rubeus.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/Seatbelt.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SharpChrome.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpChrome.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/Rubeus.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpDump.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpUp.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SharpDPAPI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpChrome.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SharpWMI.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/LockLess.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/Rubeus.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v3.5\ compiled\ binaries/SafetyKatz.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/dotnet\ v4.5\ compiled\ binaries/SafetyKatz.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/SafetyKatz.exe
/home/a/acer/typelib/repos/Ghostpack-CompiledBinaries/Seatbelt.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/Decryptor/bin/Debug/Decryptor.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/Decryptor/obj/Debug/Decryptor.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/OutFiles/runit.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/EncryptShellCode/bin/Debug/EncryptShellCode.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/EncryptShellCode/obj/Debug/EncryptShellCode.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/ShellCodeEncryptor/bin/Debug/ShellCodeEncryptor.exe
/home/a/acer/typelib/repos/OffensiveCSharp/Chapter7-EncShell/ShellCodeEncryptor/obj/Debug/ShellCodeEncryptor.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/PScript/bin/Debug/PScript.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/PScript/obj/Debug/PScript.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/PScript/obj/Release/PScript.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/PScript/bin/Release/PScript.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/client/bin/Debug/client.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/client/obj/Debug/client.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/sharpshells/bin/Debug/sharpshells.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/sharpshells/obj/Debug/sharpshells.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/psconsole/bin/Debug/psconsole.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/psconsole/obj/Debug/psconsole.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/psconsole/obj/Release/psconsole.exe
/home/a/acer/typelib/repos/OffensiveCSharp/PScript/psconsole/bin/Release/psconsole.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/InstallUtilTest/bin/Debug/goinstut.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/InstallUtilTest/obj/Debug/InstallUtilTest.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/Consoleinst/bin/Debug/Consoleinst.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/Consoleinst/obj/Debug/Consoleinst.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/buildit/bin/Debug/buildit.exe
/home/a/acer/typelib/repos/OffensiveCSharp/InstallUtilTest/buildit/obj/Debug/buildit.exe
/home/a/acer/typelib/repos/OffensiveCSharp/SharpServer/SharpServer/SharpServer/bin/Debug/SharpServer.exe
/home/a/acer/typelib/repos/OffensiveCSharp/SharpServer/SharpServer/SharpServer/obj/Debug/SharpServer.exe
/home/a/acer/typelib/repos/OffensiveCSharp/XsltTest/XsltTest/bin/Debug/XsltTest.exe
/home/a/acer/typelib/repos/OffensiveCSharp/XsltTest/XsltTest/obj/Debug/XsltTest.exe
/home/a/acer/typelib/repos/sharpwmi/sharpwmi/sharpwmi/obj/Release/sharpwmi.exe
/home/a/acer/typelib/repos/sharpwmi/sharpwmi/sharpwmi/bin/Release/sharpwmi.exe
/home/a/acer/typelib/repos/Stracciatella/Stracciatella.exe
/home/a/acer/typelib/repos/logger/Logger/bin/Debug/Logger.exe
/home/a/acer/typelib/repos/logger/Logger/obj/Debug/Logger.exe
/home/a/acer/typelib/repos/Internal-Monologue/InternalMonologueExe/bin/Release/InternalMonologue.exe
/home/a/acer/typelib/repos/Internal-Monologue/InternalMonologueDll/bin/Release/InternalMonologueDll.dll
/home/a/acer/typelib/repos/PowerShdll/exe/bin/Release/Powershdll.exe
/home/a/acer/typelib/repos/PowerShdll/dll/bin/x64/Release/PowerShdll.dll
/home/a/acer/typelib/repos/PowerShdll/dll/bin/x86/Release/PowerShdll.dll
/home/a/acer/typelib/repos/CsharpAmsiBypass/CsharpAmsiBypass/bin/Debug/CsharpAmsiBypass.exe
/home/a/acer/typelib/repos/CsharpAmsiBypass/CsharpAmsiBypass/obj/Debug/CsharpAmsiBypass.exe
/home/a/acer/typelib/repos/RedSharp/SharpThrough/obj/x64/Debug/sharpthrough.exe
/home/a/acer/typelib/repos/RedSharp/SharpThrough/bin/x64/Debug/sharpthrough.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/bin/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/bin/x64/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/bin/x64/Debug/sharpthrough.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/bin/x86/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/obj/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/obj/x64/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/obj/x64/Debug/sharpthrough.exe
/home/a/acer/typelib/repos/RedSharp/SharpMeter/obj/x86/Debug/sharpmeter.exe
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/bin/Release/app.publish/ClickOnceSQL.exe
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/bin/Release/ClickOnceSQL.exe
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/obj/Debug/ConsoleApplication2.exe
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/obj/Release/ClickOnceSQL.exe
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/Application\ Files/ClickOnceSQL_1_0_0_5/ClickOnceSQL.exe.deploy
/home/a/acer/typelib/repos/ESC/ClickOnceSQL/bin/Release/app.publish/Application\ Files/ClickOnceSQL_1_0_0_5/ClickOnceSQL.exe.deploy
/home/a/acer/typelib/repos/GrayKeylogger/Gray\ Keylogger\ Compiled/Gray\ Keylogger\ 3.exe
/home/a/acer/typelib/repos/bantam/Bins/bantam.exe
/home/a/acer/typelib/repos/WindowsPlague/bin/WindowsPlague.exe
/home/a/acer/typelib/repos/TikiTorch/Aggressor/Templates/TikiSpawnWOppid.dll
/home/a/acer/typelib/repos/TikiTorch/Aggressor/Templates/TikiSpawnWppid.dll
/home/a/acer/typelib/repos/HiveJack/bin/Debug/HiveJack.exe
/home/a/acer/typelib/repos/HiveJack/obj/Debug/HiveJack.exe
/home/a/acer/typelib/repos/HiveJack/bin/Release/HiveJack.exe
/home/a/acer/typelib/repos/HiveJack/obj/Release/HiveJack.exe
/home/a/acer/typelib/repos/DecryptAutoLogon/DecryptAutoLogon/bin/Release/DecryptAutoLogon.exe
/home/a/acer/typelib/repos/DecryptAutoLogon/DecryptAutoLogon/obj/Release/DecryptAutoLogon.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/sharpshares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpHound.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpBlock.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpHound.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/Snaffler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpBlock.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpBlock.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpHound.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x64/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_Any/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x64/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/sharpshares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpBlock.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/Snaffler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpSvc.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/ADSearch.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpSvc.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/ADSearch.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.5_x86/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/LockLess.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/Rubeus.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/Watson.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/scout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpTask.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/StandIn.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpStay.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpWMI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/BetterSafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpCrashEventLog.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpUp.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpSpray.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpSvc.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpMove.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/ADSearch.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpHandler.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpAllowedToAct.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpDir.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/TruffleSnout.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/ThunderFox.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpMiniDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpReg.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpCookieMonster.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/winPEAS.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/AtYourService.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/Seatbelt.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharPersist.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpHose.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpSecDump.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpKatz.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpMapExec.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpShares.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpRDP.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpChromium.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/StickyNotesExtract.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpChrome.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SweetPotato.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpGPOAbuse.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x64/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_x86/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.7_Any/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_x86/SharpChisel.exe
/home/a/acer/typelib/repos/SharpCollection/NetFramework_4.0_Any/SharpChisel.exe
/home/a/acer/typelib/repos/RAT-NjRat-0.7d-modded-source-code/APP\ -\ NjRat\ 0.7D\ Moded/NjRat\ 0.7D.exe
/home/a/acer/typelib/repos/BypassUAC/BypassUAC_Dll_csharp/obj/x64/Release/BypassUAC_Dll_csharp.dll
/home/a/acer/typelib/repos/BypassUAC/x64/Release/BypassUAC_Dll_csharp.dll
/home/a/acer/typelib/repos/BypassUAC/x64/Release/BypassUAC_csharp.exe
/home/a/acer/typelib/repos/hanzoInjection/HanzoInjection.exe
/home/a/acer/typelib/repos/EasyNet/EasyNet/bin/Debug/EasyNet.exe
/home/a/acer/typelib/repos/EasyNet/EasyNet/bin/Debug/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/EasyNet/bin/Release/EasyNet.exe
/home/a/acer/typelib/repos/EasyNet/EasyNet/bin/Release/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/EasyNet/obj/Debug/EasyNet.exe
/home/a/acer/typelib/repos/EasyNet/EasyNet/obj/Release/EasyNet.exe
/home/a/acer/typelib/repos/EasyNet/EasyNetLibrary/bin/Debug/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/EasyNetLibrary/bin/Release/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/EasyNetLibrary/obj/Debug/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/EasyNetLibrary/obj/Release/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/bin/Debug/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/bin/Debug/ExampleWrapper.exe
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/bin/Release/EasyNetLibrary.dll
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/bin/Release/ExampleWrapper.exe
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/obj/Debug/ExampleWrapper.exe
/home/a/acer/typelib/repos/EasyNet/ExampleWrapper/obj/Release/ExampleWrapper.exe
/home/a/acer/typelib/repos/SharpByeBear/packages/NtApiDotNet.1.1.21/lib/net45/NtApiDotNet.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/bin/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/bin/x64/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/bin/x86/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/bin/x86/Release/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/obj/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/obj/Release/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/obj/x64/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/obj/x86/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpByeBear/CollectorService/obj/x86/Release/SystemCollector.dll
/home/a/acer/typelib/repos/Telegra_Csharp_C2/TGbot/obj/Debug/TGbot.exe
/home/a/acer/typelib/repos/Telegra_Csharp_C2/TGbot/bin/Debug/TGbot.exe
/home/a/acer/typelib/repos/SharpClipboard/SharpClipboard/obj/Release/SharpClipboard.exe
/home/a/acer/typelib/repos/SharpCompile/SharpCompileServer/SharpCompileServer/obj/Debug/SharpCompileServer.exe
/home/a/acer/typelib/repos/SharpCompile/SharpCompileServer/SharpCompileServer/bin/Debug/SharpCompileServer.exe
/home/a/acer/typelib/repos/SharpPack/SharpSql/SharpSql/bin/Debug/SharpSql.exe
/home/a/acer/typelib/repos/SharpPack/SharpSql/SharpSql/obj/Debug/SharpSql.exe
/home/a/acer/typelib/repos/SharpPack/SharpCradle/CompiledBinaries/SharpCradle_x64.exe
/home/a/acer/typelib/repos/SharpPack/SharpCradle/CompiledBinaries/SharpCradle_x86.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/Resources/csexecsvc-net35.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/Resources/csexecsvc-net40.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/Resources/csexecsvc-net45.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/bin/Release/net35/csexec.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/bin/Release/net45/csexec.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/obj/Release/csexec.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexec/bin/Release/net40/csexec.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexecsvc/bin/Release/net45/csexecsvc.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexecsvc/bin/Release/net35/csexecsvc.exe
/home/a/acer/typelib/repos/SharpPack/CSExec/csexecsvc/obj/Release/csexecsvc.exe
/home/a/acer/typelib/repos/SharpPack/SharpSploitConsole/CompiledBinaries/SharpSploitConsole_x64.exe
/home/a/acer/typelib/repos/SharpPack/SharpSploitConsole/CompiledBinaries/SharpSploitConsole_x86.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpRoast.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/CSExec/csexec/net45/csexec.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/CSExec/csexec/net40/csexec.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/CSExec/csexecsvc/net45/csexecsvc.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/CSExec/csexecsvc/net35/csexecsvc.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpCradle/SharpCradle_x86.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpDump.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpSql.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpDPAPI.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpChrome.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/Rubeus.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/CSExec/csexec/net35/csexec.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpCradle/SharpCradle_x64.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpUp.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpWMI.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpWMI.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/Seatbelt.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpSploitConsole/SharpSploitConsole_x64.exe
/home/a/acer/typelib/repos/SharpPack/Binaries/SharpSploitConsole/SharpSploitConsole_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET3.5/SalseoLoader_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET4.0/SalseoLoader_x64.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET4.0/SalseoLoader_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET4.5/SalseoLoader_x64.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET4.5/SalseoLoader_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SilentMOD/NET4.5/SilentMOD_x64.dll
/home/a/acer/typelib/repos/Salsa-tools/releases/SilentMOD/NET4.5/SilentMOD_x86.dll
/home/a/acer/typelib/repos/Salsa-tools/releases/Standalone/NET4.0/SalseoStandalone_x64.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/Standalone/NET4.0/SalseoStandalone_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/Standalone/NET4.5/SalseoStandalone_x64.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/Standalone/NET4.5/SalseoStandalone_x86.exe
/home/a/acer/typelib/repos/Salsa-tools/releases/SalseoLoader/NET3.5/SalseoLoader_x64.exe
/home/a/acer/typelib/repos/BlockEtw/blocketw/obj/Release/blocketw.exe
/home/a/acer/typelib/repos/VanillaRAT/VanillaRat/bin/Debug/VanillaStub.exe
/home/a/acer/typelib/repos/VanillaRAT/VanillaRat/obj/Debug/VanillaRat.exe
/home/a/acer/typelib/repos/VanillaRAT/VanillaRat/bin/Debug/VanillaRat.exe
/home/a/acer/typelib/repos/VanillaRAT/VanillaStub/bin/Debug/VanillaStub.exe
/home/a/acer/typelib/repos/VanillaRAT/VanillaStub/obj/Debug/VanillaStub.exe
/home/a/acer/typelib/repos/CSPlugins/Aggressor/Cscan.exe
/home/a/acer/typelib/repos/CSPlugins/Erebus-master/post/Seatbelt.exe
/home/a/acer/typelib/repos/CSPlugins/Erebus-master/post/SafetyKatz.exe
/home/a/acer/typelib/repos/SharpPolarBear/packages/NtApiDotNet.1.1.21/lib/net45/NtApiDotNet.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/bin/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/bin/x64/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/bin/x86/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/obj/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/obj/x64/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/SharpPolarBear/CollectorService/obj/x86/Debug/SystemCollector.dll
/home/a/acer/typelib/repos/Sharp-Suite/SwampThing/obj/Release/SwampThing.exe
/home/a/acer/typelib/repos/rat-shell/Binaries/rat.exe
/home/a/acer/typelib/repos/rat-shell/Binaries/controller.exe
/home/a/acer/typelib/repos/DLL-Injector/Com.Xenthrax.DllInjector.Example/bin/Debug/Com.Xenthrax.DllInjectorTest.exe
/home/a/acer/typelib/repos/DLL-Injector/bin/Debug/Com.Xenthrax.DllInjector.dll
/home/a/acer/typelib/repos/DLL-Injector/Com.Xenthrax.DllInjector.Example/bin/Debug/Com.Xenthrax.DllInjector.Example.exe
/home/a/acer/typelib/repos/DLL-Injector/Com.Xenthrax.DllInjector.Example/bin/Debug/Com.Xenthrax.DllInjector.Test.exe
/home/a/acer/typelib/repos/DLL-Injector/Com.Xenthrax.DllInjector.Example/bin/Debug/Com.Xenthrax.DllInjector.dll
/home/a/acer/typelib/repos/AllTheThings/AllTheThings/bin/Debug/AllTheThings.exe
/home/a/acer/typelib/repos/AllTheThings/AllTheThings/bin/x64/Release/AllTheThings.dll
/home/a/acer/typelib/repos/AllTheThings/AllTheThings/obj/Debug/AllTheThings.exe
/home/a/acer/typelib/repos/AllTheThings/AllTheThings/obj/x64/Release/AllTheThings.dll
/home/a/acer/typelib/repos/Random-CSharpTools/NetDump/NetDump/Microsoft.Diagnostics.Runtime.dll
/home/a/acer/typelib/repos/Random-CSharpTools/NetDump/NetDump/obj/Release/NetDump.exe.tmp
/home/a/acer/typelib/repos/Random-CSharpTools/NetDump/NetDump/obj/x64/Release/NetDump.exe.tmp
/home/a/acer/typelib/repos/Random-CSharpTools/CyDuck/CyDuck/obj/Debug/CyDuck.exe.tmp
/home/a/acer/typelib/repos/Random-CSharpTools/CyDuck/CyDuck/obj/Release/CyDuck.exe.tmp
/home/a/acer/typelib/repos/Random-CSharpTools/CyDuck/CyDuck/Microsoft.Diagnostics.Runtime.dll
/home/a/acer/typelib/repos/Random-CSharpTools/CyDuck/CyDuck/obj/x64/Release/CyDuck.exe.tmp
/home/a/acer/typelib/repos/Random-CSharpTools/DllLoader/DllLoader/obj/Release/DllLoader.dll
/home/a/acer/typelib/repos/Random-CSharpTools/DllLoader/DllLoader/bin/Release/DllLoader.dll
/home/a/acer/typelib/repos/RAT.TelegramSpyBot/RAT\ TelegramSpyBot/obj/Debug/RAT\ TelegramSpyBot.exe
/home/a/acer/typelib/repos/RAT.TelegramSpyBot/RAT\ TelegramSpyBot/obj/Debug/RAT_BotTelegram.exe
/home/a/acer/typelib/repos/RAT.TelegramSpyBot/RAT\ TelegramSpyBot/bin/Debug/RAT\ TelegramSpyBot.exe
/home/a/acer/typelib/repos/TheHackToolBoxTeek/ExePumpTeek/Download/Exe\ Pump\ Teek.exe
/home/a/acer/typelib/repos/TheHackToolBoxTeek/netAssemblyDetect/Download/netAssemblyDetect.exe
/home/a/acer/typelib/repos/TheHackToolBoxTeek/EntropyCalcExe/EntropyCalcExe/bin/Release/entropyCalcExe.exe
/home/a/acer/typelib/repos/TheHackToolBoxTeek/lib/common/helpers/SearchDirectory/SearchDirectory/bin/Debug/SearchDirectory.dll
/home/a/acer/typelib/repos/TheHackToolBoxTeek/lib/common/helpers/Randomize/bin/Debug/Randomize.dll
/home/a/acer/typelib/repos/TheHackToolBoxTeek/exe2bytes/Donwload/exe2bytes.exe
/home/a/acer/typelib/repos/TheHackToolBoxTeek/Exe2Base64/Exe2Base64/bin/Release/exe2Base64.exe
/home/a/acer/typelib/repos/IIS_backdoor/bin/IIS_backdoor_shell.exe
/home/a/acer/typelib/repos/IIS_backdoor/bin/IIS_backdoor_dll.dll
/home/a/acer/typelib/repos/SharpSocks/Binaries/SharpSocksServerTestApp/SharpSocksServerTestApp.exe
/home/a/acer/typelib/repos/SharpSocks/Binaries/SharpSocksServerTestApp/SharpSocksServer.dll
/home/a/acer/typelib/repos/SharpSocks/Binaries/SharpSocksServerDLL/SharpSocksServer.dll
/home/a/acer/typelib/repos/DoHC2/Example-Client/DoHC2Runner/obj/Debug/DoHC2Runner.exe
/home/a/acer/typelib/repos/KeeThief/KeePass-2.34-Source-Patched/Translation/TrlUtil.exe
/home/a/acer/typelib/repos/KeeThief/KeeTheft/KeeTheft/Microsoft.Diagnostics.Runtime.v3.5.dll
/home/a/acer/typelib/repos/SyscallPOC/Syscall/bin/Debug/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Syscall/bin/Release/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Syscall/obj/Debug/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Syscall/obj/Release/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/obj/Release/Win32-Injector.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/bin/Release/Win32-Injector.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/Syscall/obj/Release/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/Syscall/bin/Debug/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/Syscall/bin/Release/Syscall.exe
/home/a/acer/typelib/repos/SyscallPOC/Win32-Injector/Syscall/obj/Debug/Syscall.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/documenation-app/ScanProjectManagement/ScanProjectManagement/obj/Debug/ScanProjectManagement.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/documenation-app/ScanProjectManagement/ScanProjectManagement/bin/Debug/ScanProjectManagement.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/powershell/PowerShell/bin/Debug/cmd.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/powershell/PowerShell/bin/Release/cmd.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/GetUserCreds/GetUserCreds/bin/Debug/GetUserCreds.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/GetUserCreds/GetUserCreds/obj/Debug/GetUserCreds.exe
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/dynamic-exe/dynamic-code/BadMojo/bin/Debug/BadMojo.dll
/home/a/acer/typelib/repos/Pen-Test-Tools/exe-dot-net/dynamic-exe/dynamic-code/BadMojo/bin/Release/BadMojo.dll
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye/bin/Debug/GoldenEye.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye/bin/Debug/GoldenEye.exe_protected.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye/obj/Debug/GoldenEye.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye/obj/Debug/Huna.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye/obj/x86/Debug/GoldenEye.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/NoisetteCLI/bin/Debug/NoisetteCLI.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/NoisetteCLI/obj/Debug/NoisetteCLI.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/NoisetteCLI/bin/Debug/NoisetteCore.dll
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/Debug/bin/NoisetteCLI.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/Noisette/obj/Debug/NoisetteCore.dll
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/Noisette/bin/Debug/Noisette\ -\ Copie.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-master/Debug/bin/NoisetteCore.dll
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye\ Remote\ Administration\ Tool/GoldenEye\ Licensing\ Server/obj/Debug/GoldenEye\ Licensing\ Server.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye\ Remote\ Administration\ Tool/GoldenEye\ Licensing\ Server/bin/Debug/GoldenEye\ Licensing\ Server.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye\ Remote\ Administration\ Tool/GoldenEye\ Remote\ Administration\ Tool/bin/Debug/uiui.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye\ Remote\ Administration\ Tool/GoldenEye\ Remote\ Administration\ Tool/obj/Debug/GoldenEye\ Remote\ Administration\ Tool.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/GoldenEye\ Remote\ Administration\ Tool/GoldenEye\ Remote\ Administration\ Tool/bin/Debug/GoldenEye\ Remote\ Administration\ Tool.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-1.0.0/Noisette/bin/Debug/Noisette.exe
/home/a/acer/typelib/repos/The-Collection/Source\ Codes/Rats/Golden\ Eye/Golden\ Eye/Noisette-Obfuscator-1.0.0/Noisette/obj/Debug/Noisette.exe
/home/a/acer/typelib/repos/Change-Lockscreen/Change-Lockscreen/Change-Lockscreen/bin/Release/Change-Lockscreen.exe
/home/a/acer/typelib/repos/Change-Lockscreen/Change-Lockscreen/Change-Lockscreen/obj/Release/Change-Lockscreen.exe
/home/a/acer/typelib/repos/Keylogger/Keylogger/bin/Debug/Keylogger.exe
/home/a/acer/typelib/repos/CVE-2020-1337/BinaryPlanting/packages/NtApiDotNet.1.1.27/lib/net45/NtApiDotNet.dll
/home/a/acer/typelib/repos/CVE-2020-1337/BinaryPlanting/BinaryPlanting/bin/x64/Release/BinaryPlanting.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC20.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC35.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC40.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC45.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC46.exe
/home/a/acer/typelib/repos/PortTran/Bin/C/PortTranC30.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS30.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS40.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS45.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS46.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS20.exe
/home/a/acer/typelib/repos/PortTran/Bin/S/PortTranS35.exe
/home/a/acer/typelib/repos/DarkFender/DarkFender/bin/Debug/DarkFender.exe
/home/a/acer/typelib/repos/DarkFender/DarkFender/obj/Debug/DarkFender.exe
/home/a/acer/typelib/repos/MinerDropper/Hide/Hide/bin/Debug/Hide.exe
/home/a/acer/typelib/repos/MinerDropper/Hide/Hide/obj/Debug/Hide.exe
/home/a/acer/typelib/repos/MinerDropper/Dropper/Dropper/bin/Debug/Dropper.exe
/home/a/acer/typelib/repos/MinerDropper/Dropper/Dropper/obj/Debug/Dropper.exe
/home/a/acer/typelib/repos/SharpDomainSpray/bin/Release/SharpDomainSpray.exe
